Repository likelion-devone/snappy, pull requests merged in 2022-12, with the labels that each got.

#1 :wrench: config: eslint + prettier 설정 및 기본 프로젝트 설정
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierrc.json
  .vscode/.settings.json
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.jsx
  src/index.jsx
Labels: :wrench: 설정

#6 🎨 style: 리셋스타일 업로드
  package-lock.json
  package.json
  src/style/GlobalStyle.jsx
Labels: 🎨 HTML&CSS

#13 ✨ feat: 로그인 인풋 컴포넌트
  src/component/common/Input/AuthInput/AuthInput.jsx
  src/component/common/Input/index.jsx
Labels: :sparkles: 기능 추가

#16 ✨ feat: ValidationInput 컴포넌트
  package-lock.json
  package.json
  src/component/common/Input/AuthInput/index.jsx
  src/component/common/Input/ValidationInput/ErrorMessage/index.jsx
  src/component/common/Input/ValidationInput/index.jsx
  src/component/common/Input/index.jsx
  src/hook/useValidationInput.js
Labels: :sparkles: 기능 추가

#14 :art: style: 글로벌 theme 추가
  src/App.jsx
  src/style/GlobalStyle.jsx
  src/style/font.css
  src/style/theme.js
Labels: 🎨 HTML&CSS

#19 :art: style: Snappy Logo
  src/asset/badge-20x20.svg
  src/asset/basic-profile-img-110x110.svg
  src/asset/basic-profile-img-36x36.svg
  src/asset/basic-profile-img-42x42.svg
  src/asset/basic-profile-img-50x50.svg
  src/asset/symbole-logo-172x213.svg
  src/asset/symbole-logo-203x220.svg
  src/asset/symbole-logo-212x262.svg
  src/asset/symbole-logo2-212x262.svg
Labels: 🎨 HTML&CSS

#20 ✨ feat: Layout 및 Router 설정
  public/index.html
  src/App.jsx
  src/component/common/GlobalNav.jsx
  src/component/common/TopNav.jsx
  src/constant/route.js
  src/constant/style.js
  src/page/404/index.jsx
  src/page/Chat/index.jsx
  src/page/Home/index.jsx
  src/page/Landing/index.jsx
  src/page/Login/index.jsx
  src/page/Post/index.jsx
  src/page/Profile/index.jsx
  src/page/Router.jsx
  src/style/GlobalStyle.jsx
Labels: :wrench: 설정, :sparkles: 기능 추가

#12 ✨ feat: 프로필 컴포넌트
  src/component/common/BigProfile/FollowCounter/index.jsx
  src/component/common/BigProfile/index.jsx
  src/component/common/SmallProfile/Side/Title/index.jsx
  src/component/common/SmallProfile/Side/index.jsx
  src/component/common/SmallProfile/index.jsx
  src/constant/size.js
Labels: :sparkles: 기능 추가

#4 ✨ feat: 버튼 컴포넌트
  src/components/common/Button/Button.jsx
Labels: :sparkles: 기능 추가

#23 🌱 chore: LabeledInput 네이밍 수정
  src/component/common/Input/LabeledInput/index.jsx
  src/component/common/Input/ValidationInput/ErrorMessage/index.jsx
  src/component/common/Input/ValidationInput/index.jsx
  src/component/common/Input/index.jsx
Labels: 🌱 ETC

#24 ✨ feat: Icons 컴포넌트
  package.json
  scripts/createIconMap.js
  src/asset/icon/icon-arrow-left.svg
  src/asset/icon/icon-close.svg
  src/asset/icon/icon-edit.svg
  src/asset/icon/icon-facebook.svg
  src/asset/icon/icon-google.svg
  src/asset/icon/icon-heart.svg
  src/asset/icon/icon-home.svg
  src/asset/icon/icon-image.svg
  src/asset/icon/icon-img-layers.svg
  src/asset/icon/icon-message-circle.svg
  src/asset/icon/icon-more-vertical.svg
  src/asset/icon/icon-post-album.svg
  src/asset/icon/icon-post-list.svg
  src/asset/icon/icon-search.svg
  src/asset/icon/icon-share.svg
  src/asset/icon/icon-user.svg
  src/asset/icon/icons.js
Labels: :sparkles: 기능 추가

#28 🌱 chore: 게시글 컴포넌트 기본 이미지 추가
  .github/pull_request_template.md
  src/asset/icon/icon-post-img.svg
Labels: 🌱 ETC

#29 ♻️ refactor: Profile 컴포넌트 div 최소화, 아웃라인 반영
  src/component/common/BigProfile/FollowCounter/index.jsx
  src/component/common/BigProfile/index.jsx
  src/component/common/SmallProfile/Side/Title/index.jsx
  src/component/common/SmallProfile/Side/index.jsx
  src/component/common/SmallProfile/index.jsx
Labels: ♻️ 리팩토링

#31 🎨 style: AlertModal Button 개수에 따른 대응
  src/component/common/AlertModal/index.jsx
Labels: 🎨 HTML&CSS

#33 🎨 style: SmallProfile.Side.Title에서 title과 subtitle간의 간격 대응
  src/component/common/SmallProfile/Side/Title/index.jsx
Labels: 🎨 HTML&CSS

#35 ✨ feat: API fetch 관련 훅 개발 및 로그인 구현
  src/App.jsx
  src/component/common/AuthProvider/index.jsx
  src/constant/storage_keys.js
  src/hook/useAPI.js
  src/hook/useAuthInfo.js
  src/hook/useFetch.js
  src/index.jsx
  src/lib/api/index.js
  src/lib/auth/index.js
  src/lib/storage/localStorage.js
  src/page/Router.jsx
Labels: :sparkles: 기능 추가

#37 ♻️ refactor: useValidationInput 리턴 배열로 변경 및 flag 리턴 추가
  src/hook/useValidationInput.js
Labels: :sparkles: 기능 추가, ♻️ 리팩토링

#38 🎨 style: 로고png 파일로 변경
  src/asset/badge-20x20.png
  src/asset/badge-20x20.svg
  src/asset/basic-profile-img-110x110.svg
  src/asset/basic-profile-img-36x36.svg
  src/asset/basic-profile-img-42x42.svg
  src/asset/basic-profile-img-50x50.svg
  src/asset/logo-404-203220.png
  src/asset/logo-bw-212262.png
  src/asset/logo-main-212262.png
  src/asset/logo-profile-172213.png
  src/asset/profile-img-110.png
  src/asset/profile-img-36.png
  src/asset/profile-img-42.png
  src/asset/profile-img-50.png
  src/asset/symbole-logo-172x213.svg
  src/asset/symbole-logo-203x220.svg
  src/asset/symbole-logo-212x262.svg
  src/asset/symbole-logo2-212x262.svg
Labels: 🎨 HTML&CSS

#39 ✨ feat: 게시물 컴포넌트 마크업 및 기능 구현
  src/asset/logo-404-343264.png
  src/component/common/PostCard/index.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#42 ♻️ chore: Button 컴포넌트 사용법 변경 및 상수 변경
  src/component/common/Button/index.jsx
  src/component/common/Button/style.jsx
  src/constant/button_state.js
  src/constant/size.js
Labels: 🌱 ETC

#44 🎨 style: GlobalNav 스타일
  src/component/common/Layout/GlobalNav/component/NavIcons/index.jsx
  src/component/common/Layout/GlobalNav/component/NavLink/constant.js
  src/component/common/Layout/GlobalNav/component/NavLink/index.jsx
  src/component/common/Layout/GlobalNav/component/index.jsx
  src/component/common/Layout/GlobalNav/index.jsx
  src/component/common/Layout/index.jsx
Labels: 🎨 HTML&CSS

#48 ✨ feat: 랜딩 페이지 개발
  src/asset/title-main-291051.png
  src/component/common/Layout/index.jsx
  src/lib/auth/AuthProvider/index.jsx
  src/page/Landing/index.jsx
  src/page/Router.jsx
Labels: :sparkles: 기능 추가

#54 🐛 fix: useValidationInput cleanup 오류
  src/hook/useValidationInput.js
Labels: 🐞 버그 수정

#49 ♻️ refactor: 프로필 컴포넌트 링크 구현, 에러 이미지 핸들링+ (사용법 참고)
  src/component/common/BigProfile/FollowCounter/index.jsx
  src/component/common/BigProfile/FollowLink/index.jsx
  src/component/common/BigProfile/index.jsx
  src/component/common/SmallProfile/Side/Title/index.jsx
  src/component/common/SmallProfile/index.jsx
Labels: ♻️ 리팩토링

#55 🎨 style: AlertModal 위치와 z-index 수정
  src/component/common/AlertModal/index.jsx
Labels: 🎨 HTML&CSS

#58 ✨feat: UploadImageLabel 추가
  src/component/common/BigProfile/UploadProfileImageLabel/index.jsx
  src/component/common/BigProfile/index.jsx
Labels: :sparkles: 기능 추가

#59 🎨 style: button style state 상수 수정
  src/component/common/Button/style.jsx
  src/constant/button_state.js
Labels: 🎨 HTML&CSS

#56 ✨ feat: 드롭다운 컴포넌트 기본 구현
  src/component/common/DropdownModal/Button/index.jsx
  src/component/common/DropdownModal/index.jsx
  src/hook/useDropdownModal.js
Labels: :sparkles: 기능 추가

#63 ✨feat: 로그인 페이지 구현
  src/asset/social/facebook.png
  src/asset/social/google.png
  src/asset/social/kakao.png
  src/component/Login/Layout/index.jsx
  src/component/Login/LoginButton/index.jsx
  src/component/Login/LoginModal/index.jsx
  src/component/common/BigProfile/UploadProfileImageLabel/index.jsx
  src/component/common/Input/ValidationInput/ErrorMessage/index.jsx
  src/component/common/Layout/GlobalNav/component/NavLink/constant.js
  src/component/common/Layout/GlobalNav/component/NavLink/index.jsx
  src/component/common/Layout/index.jsx
  src/constant/route.js
  src/constant/style.js
  src/hook/useValidationInput.js
  src/lib/api/index.js
  src/lib/auth/AuthProvider/index.jsx
  src/lib/auth/index.js
  src/page/Login/Authorize/index.jsx
  src/page/Login/Join/[pagenum]/1.jsx
  src/page/Login/Join/[pagenum]/2.jsx
  src/page/Login/Join/[pagenum]/index.jsx
  src/page/Login/Join/index.jsx
  src/page/Login/index.jsx
  src/page/Router.jsx
  src/util/validation.js
Labels: :sparkles: 기능 추가, ♻️ 리팩토링

#61 ✨feat: 게시물 페이지 분리 및 개발
  src/component/Post/ImgDataProvider/index.jsx
  src/component/Post/IsUploadPossibleProvider/index.jsx
  src/component/Post/LabelImgUpload/index.jsx
  src/component/Post/TextArea/index.jsx
  src/component/Post/TextArea/style.jsx
  src/component/common/AddedImgList/index.jsx
  src/component/common/PostCard/index.jsx
  src/page/Home/index.jsx
  src/page/Post/Upload/index.jsx
  src/page/Post/[postId]/index.jsx
  src/page/Post/index.jsx
  src/page/Router.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#64 ✨feat: TopNav 컴포넌트 개발 및 SearchBar 컴포넌트 개발
  src/component/Home/SearchBar/ResultCard/index.jsx
  src/component/Home/SearchBar/index.jsx
  src/component/common/Layout/GlobalNav/component/index.jsx
  src/component/common/Layout/index.jsx
  src/component/common/Navbar/GlobalNav/component/NavIcons/index.jsx
  src/component/common/Navbar/GlobalNav/component/NavLink/constant.js
  src/component/common/Navbar/GlobalNav/component/NavLink/index.jsx
  src/component/common/Navbar/GlobalNav/component/index.jsx
  src/component/common/Navbar/GlobalNav/index.jsx
  src/component/common/Navbar/TopNav/Button/GoBackButton/index.jsx
  src/component/common/Navbar/TopNav/Button/MoreButton/index.jsx
  src/component/common/Navbar/TopNav/Button/SearchButton/index.jsx
  src/component/common/Navbar/TopNav/Button/index.jsx
  src/component/common/Navbar/TopNav/Title/index.jsx
  src/component/common/Navbar/TopNav/index.jsx
  src/component/common/Navbar/TopNavProvider/index.jsx
  src/component/common/Navbar/index.jsx
  src/component/common/Navbar/style/css.js
  src/component/common/SmallProfile/index.jsx
  src/component/common/TopNav.jsx
  src/hook/useTopNavSetter.js
  src/lib/auth/index.js
  src/page/Home/index.jsx
  src/page/Login/Join/[pagenum]/2.jsx
  src/style/theme.js
Labels: :sparkles: 기능 추가

#60 🎨 style: 404 UI
  src/page/404/index.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#69 ✨ feat: 게시물 컴포넌트 드롭다운 모달 적용 및 getTimeGapInKr 유틸 함수 추가
  src/component/common/PostCard/index.jsx
  src/page/Home/index.jsx
  src/util/getTimeGapInKr.js
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS, ♻️ 리팩토링

#75 ✨ feat: 댓글 작성, 신고, 삭제 기능 추가 및 CommentForm 스타일 변경
  src/component/Post/Comment/CommentCard/index.jsx
  src/component/Post/CommentCard/index.jsx
  src/component/common/CommentForm/index.jsx
  src/component/common/Input/CommentInput/index.jsx
  src/page/Chat/ChatRoom/index.jsx
  src/page/Chat/index.jsx
  src/page/Post/[postId]/index.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#81 ✨ feat: ProfileEditPage 개발
  src/component/Profile/PageDetails/index.jsx
  src/component/common/BigProfile/UploadProfileImageLabel/index.jsx
  src/component/common/BigProfile/index.jsx
  src/component/common/Form/CommentForm/index.jsx
  src/component/common/Form/ProfileForm/index.jsx
  src/constant/route.js
  src/hook/useAPI.js
  src/page/Chat/ChatRoom/index.jsx
  src/page/Login/Join/[pagenum]/2.jsx
  src/page/Login/Join/index.jsx
  src/page/Post/[postId]/index.jsx
  src/page/Profile/Edit/index.jsx
  src/page/Router.jsx
  src/util/isBlobUrl.js
  src/util/validation.js
Labels: :sparkles: 기능 추가

#80 ✨ feat: 게시물 이미지 캐러셀 스타일링 수정 및 슬라이드 버튼 기능 구현
  src/asset/icon/icon-slide-btn.svg
  src/asset/icon/icons.js
  src/component/common/PostCard/index.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#85 Fix/#84 fix join form
  src/component/Login/Layout/index.jsx
  src/component/common/Form/ProfileForm/index.jsx
  src/component/common/Form/index.jsx
  src/page/Chat/ChatRoom/index.jsx
  src/page/Login/Join/[pagenum]/2.jsx
  src/page/Post/[postId]/index.jsx
  src/page/Profile/Edit/index.jsx
Labels: 🐞 버그 수정, 🎨 HTML&CSS, ♻️ 리팩토링

#86 ✨ feat: 전체적인 레이아웃 수정, 각종 버그 픽스, 프로필 컴포넌트 팔로우/언팔로우 구현
  src/component/Login/Layout/index.jsx
  src/component/Login/LinkToLogin/index.jsx
  src/component/Login/LoginModal/index.jsx
  src/component/Product/Form/index.jsx
  src/component/Profile/AlbumListView/index.jsx
  src/component/Profile/FollowButton/index.jsx
  src/component/Profile/PageDetails/index.jsx
  src/component/common/BigProfile/index.jsx
  src/component/common/Form/ProfileForm/index.jsx
  src/component/common/Layout/index.jsx
  src/component/common/Layout/style.jsx
  src/component/common/PostCard/index.jsx
  src/component/common/SmallProfile/index.jsx
  src/constant/style.js
  src/page/Chat/ChatRoom/index.jsx
  src/page/Chat/index.jsx
  src/page/Home/index.jsx
  src/page/Login/Join/[pagenum]/1.jsx
  src/page/Login/Join/[pagenum]/2.jsx
  src/page/Post/Edit/index.jsx
  src/page/Post/[postId]/index.jsx
  src/page/Profile/Edit/index.jsx
  src/page/Profile/FollowerListPage/index.jsx
  src/page/Profile/FollowingListPage/index.jsx
  src/page/Profile/index.jsx
  src/style/GlobalStyle.jsx
  src/util/isBlobUrl.js
Labels: :sparkles: 기능 추가, 🐞 버그 수정, 🎨 HTML&CSS, ♻️ 리팩토링
