Repository likelion-devone/snappy, pull requests merged in 2023-01, with the labels that each got.

#90 ✨ feat: Carousel 애니메이션 부여
  src/component/common/Carousel/index.jsx
  src/component/common/PostCard/index.jsx
Labels: :sparkles: 기능 추가

#87 ✨ feat: 프로필 페이지 상품 모달 연결, 레이아웃 수정
  src/component/Product/Form/index.jsx
  src/component/Profile/PageDetails/index.jsx
  src/component/Profile/ProductCard/index.jsx
  src/component/Profile/ProductList/index.jsx
  src/component/common/ProductProvider/index.jsx
  src/page/Product/AddProduct/index.jsx
  src/page/Product/EditProduct/index.jsx
  src/page/Product/index.jsx
  src/page/Router.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS, ♻️ 리팩토링

#91 🎨 style: 네피 팔 흔들기, 스플래시, 로딩 효과
  src/asset/SplashWH.png
  src/asset/SplashYN.png
  src/asset/logoArm.png
  src/asset/logoBody.png
  src/component/common/Animation/LoaderNappy/index.jsx
  src/component/common/Animation/SplashNappy/index.jsx
  src/component/common/Animation/index.jsx
Labels: :sparkles: 기능 추가, 🎨 HTML&CSS

#93 🐛 fix: 게시물 수정 시 이미지 업로드 안 되던 이슈 해결
  src/page/Post/Edit/index.jsx
Labels: 🐞 버그 수정

#92 🐛 fix: 상품 수정 업로드 버튼 활성화 이슈 해결
  src/page/Product/EditProduct/index.jsx
Labels: 🐞 버그 수정

#95 ✨ feat: 댓글 변화에 따라 부분적으로 렌더링 되도록 로직 개선 및 카운트 갱신 오류
  src/component/Post/CommentCard/index.jsx
  src/component/Post/CommentWrapper/index.jsx
  src/component/common/Form/CommentForm/index.jsx
  src/component/common/PostDataProvider/PostDetailDataProvider/index.jsx
  src/page/Post/[postId]/index.jsx
Labels: :sparkles: 기능 추가, 🐞 버그 수정

#96 ✨ feat: 홈 피드 무한스크롤 개발
  src/hook/usePagination.js
  src/page/Home/index.jsx
Labels: :sparkles: 기능 추가

#100 🐛 fix: 프로필 수정시 authInfo 갱신 안되는 이슈
  src/lib/auth/AuthProvider/index.jsx
  src/page/Profile/Edit/index.jsx
Labels: 🐞 버그 수정
